# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailalias',
            options={'verbose_name_plural': 'Email aliases'},
        ),
        migrations.AddField(
            model_name='mnuser',
            name='pgp_key_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='PGP Key ID'),
        ),
        migrations.AddField(
            model_name='mnuser',
            name='yubikey_serial',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Yubikey Serial'),
        ),
    ]
