# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 22:34
from typing import List

from django.db import migrations
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0001_initial'),
        ('mailauth', '0002_stored_procedures'),
    ]

    # This migration previously granted access to the stored procedure API to users defined in the environment.
    # It has been replaced by the 'spapi' management.py command.

    operations = [
    ]  # type: List[Operation]
