# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0003_opensmtpd_access'),
        ('oauth2_provider', '0002_08_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Grant',
            name='application',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='mailauth.MNApplication')
        ),
        migrations.AlterField(
            model_name='Accesstoken',
            name='application',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='mailauth.MNApplication')
        ),
        migrations.AlterField(
            model_name='Refreshtoken',
            name='application',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='mailauth.MNApplication')
        ),
    ]

    def __init__(self, name, app_label):
        super().__init__(name, app_label)
        self.app_label = 'oauth2_provider'
