# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0003_opensmtpd_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='mnapplication',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mnapplication',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mnapplication',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
