# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0004_domain_dkimkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='dkimselector',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='DKIM DNS selector'),
        ),
    ]
