# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0004_auto_20170626_1731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MNGroups',
            new_name='MNGroup',
        ),
    ]
