# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 10:02
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0005_auto_20170709_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Descriptive name')),
                ('addresses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
            ],
        ),
        migrations.AddField(
            model_name='emailalias',
            name='forward_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mailauth.MailingList', verbose_name='Forward to list'),
        ),
    ]
