# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 11:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0006_auto_20170908_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailalias',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to=settings.AUTH_USER_MODEL),
        ),
    ]
