# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0009_auto_20170912_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='redirect_to',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Redirect all mail to domain'),
        ),
    ]
