# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0011_mnserviceuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='jwtkey',
            field=models.TextField(blank=True, verbose_name='JWT signing key (PEM)'),
        ),
    ]
