# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 12:08
from __future__ import unicode_literals

from django.db import migrations
from typing import List


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0012_domain_jwtkey'),
        ('mailauth', '0012_auto_20180320_1850'),
    ]

    operations = [
    ]  # type: List[str]
