# Generated by Django 3.2.6 on 2021-10-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0015_auto_20210412_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBlacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='This can include dashext and plusext email aliases', max_length=255, verbose_name='Email address')),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='blacklisted',
            field=models.BooleanField(default=False, verbose_name="Don't deliver to this domain"),
        ),
    ]
