# Generated by Django 4.1 on 2022-08-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0016_alter_mnapplication_client_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mnapplication',
            name='pkce_enforced',
            field=models.BooleanField(default=True, verbose_name='PKCE Required'),
        ),
    ]
