# Generated by Django 4.1 on 2022-08-29 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0017_mnapplication_pkce_enforced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mnapplication',
            name='algorithm',
        ),
        migrations.RemoveField(
            model_name='mnapplicationpermission',
            name='scope_name',
        ),
        migrations.AddField(
            model_name='mnapplication',
            name='domain',
            field=models.ForeignKey(help_text='To enable OpenID Connect, the application must be connected to (and served under) a domain instance with a JWT signing key or a parent domain with a JWT signing key and subdomain signing turned on.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mailauth.domain'),
        ),
        migrations.AddField(
            model_name='mnapplicationpermission',
            name='permission_name',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Permission identifier'),
        ),
    ]
