# Generated by Django 4.2.6 on 2023-10-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0018_remove_mnapplication_algorithm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mnapplication',
            name='post_logout_redirect_uris',
            field=models.TextField(blank=True, help_text='Allowed Post Logout URIs list, space separated'),
        ),
    ]
