# Generated by Django 6.0.1 on 2026-01-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0020_mnapplication_allowed_origins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnapplication',
            name='authorization_grant_type',
            field=models.CharField(choices=[('authorization-code', 'Authorization code'), ('urn:ietf:params:oauth:grant-type:device_code', 'Device Code'), ('implicit', 'Implicit'), ('password', 'Resource owner password-based'), ('client-credentials', 'Client credentials'), ('openid-hybrid', 'OpenID connect hybrid')], max_length=44),
        ),
    ]
