# Generated by Django 6.0.3 on 2026-03-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0022_emailalias_blacklisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='redirect_to',
            field=models.CharField(blank=True, default='', help_text='Put a domain name here to redirect all email addresses to that domain (xyz@domain.com becomes xyz@redirectdomain.com) or put an email address here to redirect all email to that one address (catch-all). Leave empty for no redirection.', max_length=255, verbose_name='Redirect all mail to domain or email'),
        ),
        migrations.AlterField(
            model_name='emailalias',
            name='blacklisted',
            field=models.BooleanField(default=False, help_text='Email to this alias will be rejected.', verbose_name='Block email'),
        ),
    ]
