# Generated by Django 6.0.3 on 2026-03-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0023_alter_domain_redirect_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='can_use_transactional_email',
            field=models.BooleanField(default=False, help_text='If enabled, this domain can use a transactional email relay configured in mailforwarder for outbound, non-forwarded (non-SRS) email. This allows using SES or similar services for sending email with higher deliverability. Please note that this flag alone is not enough, mailforwarder and your local mail server must have the necessary configuration as well.', verbose_name='Can use transactional email relay'),
        ),
    ]
