# Generated by Django 6.0.4 on 2026-04-21 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0024_domain_can_use_transactional_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL,
                                    related_name='managed_mailing_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
