# Generated by Django 6.0.4 on 2026-05-01 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0025_mailinglist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnuser',
            name='delivery_mailbox',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mailauth.emailalias'),
        ),
    ]
