# Generated by Django 6.0.4 on 2026-05-21 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0026_alter_mnuser_delivery_mailbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAgentAuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_digest', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('token_hint', models.CharField(editable=False, max_length=12)),
                ('burned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_agent_auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Agent Auth Token',
                'verbose_name_plural': 'Email Agent Auth Tokens',
                'ordering': ('-created_at',),
            },
        ),
    ]
