# Generated by Django 6.0.4 on 2026-05-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0027_emailagentauthtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailagentauthtoken',
            name='token',
            field=models.CharField(blank=True, default='', editable=False, max_length=32),
        ),
    ]
