# Generated by Django 6.0.7 on 2026-07-24 08:14

import oauth2_provider.generators
import oauth2_provider.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0028_emailagentauthtoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='mnapplication',
            name='cimd_expires_at',
            field=models.DateTimeField(blank=True, default=None, help_text='When the cached Client ID Metadata Document should be re-fetched', null=True),
        ),
        migrations.AddField(
            model_name='mnapplication',
            name='registration_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('dcr', 'Dynamic Client Registration'), ('cimd', 'Client ID Metadata Document')], default='manual', help_text='How this application was registered (manual, DCR per RFC 7591, or CIMD)', max_length=32),
        ),
        migrations.AlterField(
            model_name='mnapplication',
            name='client_id',
            field=models.CharField(db_index=True, default=oauth2_provider.generators.generate_client_id, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mnapplication',
            name='client_secret',
            field=oauth2_provider.models.ClientSecretField(blank=True, db_index=True, default=oauth2_provider.generators.generate_client_secret, help_text='Client secret for authentication', max_length=255),
        ),
    ]
