# Generated by Django 6.0.7 on 2026-07-24 09:49

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0029_mnapplication_cimd_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='cimd_auto_permissions',
            field=models.BooleanField(default=True, help_text='When a CIMD application registers on this domain, create a dedicated application permission, require it on the application, and assign it to nobody - so no user can authorize against the client until an admin grants the permission.', verbose_name='Auto-generate permissions for CIMD applications'),
        ),
        migrations.AddField(
            model_name='domain',
            name='cimd_client_hosts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text="Hosts that CIMD client_id URLs may use, in Django ALLOWED_HOSTS syntax: 'client.example.com' (exact), '.example.com' (domain and all subdomains), '*' (any host - must be set explicitly). An EMPTY list blocks all CIMD clients even when CIMD is enabled.", verbose_name='CIMD client host allowlist'),
        ),
        migrations.AddField(
            model_name='domain',
            name='cimd_enabled',
            field=models.BooleanField(default=False, help_text='Allow OAuth2 clients to self-register on this domain using Client ID Metadata Documents (their client_id is an https URL that authserver fetches). Which client hosts are acceptable is controlled by the CIMD client host allowlist below.', verbose_name='Allow CIMD client registration'),
        ),
        migrations.AlterField(
            model_name='mnapplication',
            name='domain',
            field=models.ForeignKey(blank=True, help_text='To enable OpenID Connect, the application must be connected to (and served under) a domain instance with a JWT signing key or a parent domain with a JWT signing key and subdomain signing turned on.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mailauth.domain'),
        ),
    ]
