# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DockerRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Format should be 'orgname/appname'", max_length=255, verbose_name='Name')),
                ('unauthenticated_pull', models.BooleanField(default=False, verbose_name='Allow unauthenticated pull')),
                ('unauthenticated_push', models.BooleanField(default=False, verbose_name='Allow unauthenticated push')),
            ],
        ),
    ]
