# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailauth', '0014_domain_jwt_subdomains'),
        ('dockerauth', '0002_auto_20170709_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerregistry',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mailauth.Domain'),
        ),
    ]
