# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dockerauth', '0005_remove_dockerregistry_sign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerregistry',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailauth.Domain'),
        ),
    ]
