resources:
    - name: authserver
      type: git
      source:
          uri: git@bitbucket.org:jdelic/authserver.git
          private_key: {{bitbucket_access_key}}
          branch: feature/concourse
          tag_filter: *.*.*

jobs:
    - name: authserver-deb
      plan:
          - get: authserver
            trigger: true
          - task: gopythongo
            file: authserver/.ci/concourse/gopythongo.yaml
