resource_types:
    - name: github-status
      type: docker-image
      source:
          repository: dpb587/github-status-resource
          tag: master


resources:
    - name: authserver
      type: git
      source:
          uri: https://github.com/jdelic/authserver.git
          branch: develop
    - name: github-status
      type: github-status
      source:
          access_token: ((github.access_token))
          repository: jdelic/authserver
          context: ci/concourse
          branch: develop
    - name: gopythongo-debian-etch
      type: docker-image
      source:
          repository: https://registry.maurus.net/gopythongo/gopythongo/debian-etch


jobs:
    - name: build-environment
      plan:
          - get: authserver
    - name: authserver-deb
      plan:
          - get: authserver
            trigger: true
          - put: github-status
            params:
                state: pending
                commit: authserver
          - task: gopythongo
            file: authserver/.ci/concourse/gopythongo.yaml
            params:
                APTLY_PUBLISH_ENDPOINT: s3:maurusnet:nightly/stretch
                APTLY_DISTRIBUTION: mn-nightly
                REPO: authserver
                VAULTWRAPPER_READ_PATH: secret/gpg/packaging_passphrase
            on_failure:
                put: github-status
                params:
                    state: failure
                    commit: authserver
            on_success:
                put: github-status
                params:
                    state: success
                    commit: authserver
