resource_types:
    - name: github-status
      type: docker-image
      source:
          repository: dpb587/github-status-resource
          tag: master


resources:
    - name: authserver
      type: git
      source:
          uri: git@github.com:jdelic/authserver.git
          private_key: ((github.access_key))
          branch: develop
    - name: github-status
      type: github-status
      source:
          access_token: ((github.access_token))
          repository: jdelic/authserver
          context: ci/concourse
          branch: develop


jobs:
    - name: authserver-deb
      plan:
          - get: authserver
            trigger: true
          - task: gopythongo
            file: authserver/.ci/concourse/gopythongo.yaml
            params:
                GNUPGHOME: /etc/gpg-managed-keyring/
                APTLY_PUBLISH_ENDPOINT: s3:maurusnet:nightly/stretch
                APTLY_DISTRIBUTION: mn-nightly
                REPO: authserver
                VAULTWRAPPER_READ_PATH: secret/gpg/packaging_passphrase
                VGC_OVERWRITE: 0
                VGC_XSIGN_CACERTS: postgresql.crt=/etc/concourse/cacerts/
