resource_types:
    - name: bitbucket-notify
      type: docker-image
      source:
          repository: ecometrica/concourse-resource-bitbucket
          branch: feature/concourse


resources:
    - name: authserver
      type: git
      source:
          uri: git@bitbucket.org:jdelic/authserver.git
          private_key: {{bitbucket_access_key}}

    - name: bitbucket-notify
      type: bitbucket-notify
      source:
          client_id: {{bitbucket_client_id}}
          secret: {{bitbucket_client_secret}}
          repo: jdelic/authserver


jobs:
    - name: mypy
      plan:
          - get: authserver
            trigger: true
          - put: bitbucket-notify
            params:
                state: INPROGRESS
                repo: authserver
          - task: unit
            file: .ci/concourse/mypy.yaml
            on_success:
                put: bitbucket-notify
                params:
                    state: SUCCESSFUL
                    repo: authserver
            on_failure:
                put: bitbucket-notify
                params:
                    state: FAILED
                    repo: authserver
